### ISSUE TITLE
Bug: JWT token expiration is caching to less then 60 seconds. (API object has no  attribute 'jwt_expires_at')

### ISSUE THREAD

**Issue by Hemant40** [PaloAltoNetworks/prisma_config#1]
## Describe the bug

While running the code for both Pull Site and Do site the code is raising an error for jwt token.

## Expected behavior

pull site module should get the configuration from site.
do site module should configure the site.

## Current behavior

Getting Error in code, not able to run the commands.

(prisma_config) root@worker2-vm:/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config# ./pull_site.py -S "C4I_PMI_OSAKA_SITE"
Traceback (most recent call last):
  File "./pull_site.py", line 5, in <module>
    go()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/pull.py", line 2243, in go
    pull_config_sites(args['sites'], filename, output_multi=multi_output, normalize=normalize,
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/pull.py", line 1966, in pull_config_sites
    update_global_cache()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/pull.py", line 333, in update_global_cache
    sites_resp = sdk.get.sites()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/get_api.py", line 5016, in sites
    return self._parent_class.rest_call(url, "get")
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1115, in rest_call
    if not self._refresh_jwt():
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1859, in _refresh_jwt
    if self.jwt_expires_in <= 60:
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1768, in jwt_expires_in
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
AttributeError: 'API' object has no attribute 'jwt_expires_at'

(prisma_config) root@worker2-vm:/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config# ./do_site.py  Osaka/* --destroy --declaim
WARNING: YAML file not correct type or version. Required mandatory meta attributes: type, sdk_version and config_version 
{
    "Expected Type": "prismasdwan template",
    "Read Type": "cloudgenix template",
    "Expected SDK Version": ">= 6.3.1b1",
    "Read SDK Version": "6.3.2b1",
    "Expected Config Version": ">= 6.3.1b1",
    "Read Config Version": "2.1.0b1"
}
None
Traceback (most recent call last):
  File "./do_site.py", line 6, in <module>
    go()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/do.py", line 12212, in go
    do_site(loaded_config, destroy, declaim=declaim, wait_element_config=wait_element_config, passed_apiversion=apiversion)
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/do.py", line 8107, in do_site
    update_global_cache()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/do.py", line 560, in update_global_cache
    sites_resp = sdk.get.sites()
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/get_api.py", line 5016, in sites
    return self._parent_class.rest_call(url, "get")
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1115, in rest_call
    if not self._refresh_jwt():
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1859, in _refresh_jwt
    if self.jwt_expires_in <= 60:
  File "/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan/prisma_config/prisma_config/lib/python3.8/site-packages/prisma_sase/__init__.py", line 1768, in jwt_expires_in
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
AttributeError: 'API' object has no attribute 'jwt_expires_at'

## Your Environment
(prisma_config) root@worker2-vm:/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan# python --version
**Python 3.8.10**
(prisma_config) root@worker2-vm:/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan# pull_site --version
****PROGRAM VERSIONS**, Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0], 'prisma_config' version: 6.3.1b1, 'prisma_sase' version: 6.3.1b1,
'json' version: 2.0.9, 'yaml' version: 6.0.1, 'logging' version: 0.5.1.2,

(prisma_config) root@worker2-vm:/home/ubuntu/Hemant/03_04_pmi_env_sdwan/osaka_site_sdwan# pip3 list 
Package            Version 
------------------ --------
certifi            2024.6.2
cffi               1.16.0  
cgxsh              1.0.1b1 
charset-normalizer 3.3.2   
cloudgenix         6.3.2b1 
cryptography       42.0.8  
fuzzywuzzy         0.18.0  
idna               3.7     
jinja2             3.1.4   
MarkupSafe         2.1.5   
pip                20.0.2  
pkg-resources      0.0.0   
prisma-config      6.3.1b1 
prisma-sase        6.3.1b1 
pycparser          2.22    
PyYAML             6.0.1   
requests           2.32.3  
setuptools         44.0.0  
tabulate           0.9.0   
urllib3            2.2.2   
websockets         12.0    
wheel              0.34.2

**Comment by Hemant40** [comment]
Hi, Sorry i was using wrong credential file. I am closing this issue.

**Comment by hildebrau** [comment]
I'm hitting jwt_expires_at errors, too.. what was your credential file issue?

my prismasdwan_settings.py file contains:
PRISMASDWAN_CLIENT_ID = '<removed>'
PRISMASDWAN_CLIENT_SECRET = '<removed>'
PRISMASDWAN_TSGID = '<removed>'


(venv) $ pull_site -S "ITLAB1_Austin" --output ITLAB1_Austin.yaml
WARNING: Prisma SASE Python SDK upgrade available. SDKs are often deprecated 6 months after release of a new version.
        Latest Version: 6.5.1b1
        Current Version: 6.3.1b1
        For more info, see 'https://github.com/PaloAltoNetworks/prisma-sase-sdk-python'. Additionally, this message can be suppressed by instantiating the API with API(update_check=False).

Traceback (most recent call last):
  File "/home/sdwan/sdwan_config/venv/bin/pull_site", line 8, in <module>
    sys.exit(go())
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_config/pull.py", line 2243, in go
    pull_config_sites(args['sites'], filename, output_multi=multi_output, normalize=normalize,
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_config/pull.py", line 1966, in pull_config_sites
    update_global_cache()
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_config/pull.py", line 333, in update_global_cache
    sites_resp = sdk.get.sites()
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_sase/get_api.py", line 4968, in sites
    return self._parent_class.rest_call(url, "get")
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1109, in rest_call
    if not self._refresh_jwt():
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1853, in _refresh_jwt
    if self.jwt_expires_in <= 60:
  File "/home/sdwan/sdwan_config/venv/lib64/python3.9/site-packages/prisma_sase/__init__.py", line 1762, in jwt_expires_in
    return int(round((self.jwt_expires_at - datetime.datetime.now()).total_seconds()))
AttributeError: 'API' object has no attribute 'jwt_expires_at'
